<ul>
	<h3>个人信息填写规范</h3>
	<p>
	<li>带*的为必填项。</li>
	<li>填好后单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-save'"></a>保存</li>
	</p>

	<h3>学习经历填写规范</h3>
	<p>
	<li>学习经历从大学开始填写。</li>
	<li>层次：以最后获得学历、学位为准。</li>
	</p>

	<h3>工作经历填写规范</h3>
	<p>
	<li>工作单位：填写单位全称。</li>
	<li>如还在职则离职时间不填。</li>
	</p>

	<h3>证书管理填写规范</h3>
	<p>
	<li>证书名称：如下拉选项中没有则选“其他”。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<li>查询数据：设定多个查询条件，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-search'">查找</a></li>
	</p>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a></li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a></li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a></li>
	</p>
	<p>
	<li>取消操作：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-redo'">撤销</a></li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>