<ul>
	<h3>学习经历填写规范</h3>
	<p>
	<li>学习经历从大学开始填写。</li>
	</p>
	<p>
	<li>层次：以最后获得学历、学位为准。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a>，填写完成后单击保存</li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a>
	</li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a>
	</li>
	</p>
	<p>
	<li>取消操作：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-redo'">撤销</a>
	</li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>