<ul>
	<h3>指导学生获奖填写规范</h3>
	<p>
	<li>同一个获奖项目只需填写一次。</li>
	<li>奖项：按获奖证书上面的名称填写。</li>
	<li>指导教师：使用鼠标左键双击进行添加和删除指导教师，由上往下排序。</li>
	</p>

	<h3>教学成果及奖励填写规范</h3>
	<p>
	<li>同一个获奖项目只需填写一次。</li>
	<li>获奖人：使用鼠标左键双击进行添加和删除获奖人，由上往下排序。</li>
	</p>

    <h3>科研成果及奖励填写规范</h3>
	<p>
	<li>同一个获奖项目只需填写一次。</li>
	<li>获奖人：使用鼠标左键双击进行添加和删除指导教师，由上往下排序。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a></li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a></li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a></li>
	</p>
	<p>
	<li>取消操作：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-redo'">撤销</a></li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>