<ul>

	<h3>其他工作填写规范</h3>
	<p>
	<li>工作性质：如下拉选项中没有则选择“其他”。</li>
	</p>
	<p>
	<li>工作描述：对此项工作的简单描述，如班主任则写“担任xxx班级班主任工作”。</li>
	</p>
	<p>
	<li>时间：开始做此工作的时间。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<li>查询数据：设定查询条件，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-search'">查找</a>
	</li>
	</p>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a>，填写完成后单击保存</li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a>
	</li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a>
	</li>
	</p>
	<p>
	<li>取消操作：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-redo'">撤销</a>
	</li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>