<ul>
	<h3>教材使用填写规范</h3>
	<p>
	<li>教材获奖情况：按教材封面的获奖信息填写。</li>
	</p>
	<p>
	<li>版次：填写教材出版版次，如“第2版”。</li>
	</p>
	<p>
	<li>专业/年级/班级：填写使用教材班级，单个班级如“外语A1411”，多个班级如“外语A1411/外语A1412”。</li>
	</p>
	<p>
	<li>教研室：课程所属教研室。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a>，填写完成后单击保存</li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a>
	</li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a>
	</li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>