<ul>
	<h3>教改课题填写规范</h3>
	<p>
	<li>同一个教改课题只需填写一次。</li>
	</p>
	<p>
	<li>参与者：使用鼠标左键双击进行添加和删除参与者，由上往下排序。</li>
	</p>
	<p>
	<li>立项证书和结题证书上传图片，其他材料压缩后上传附件。</li>
	</p>
	<p>
	<li><font color="#ff0000">非课题参与者不能查看课题信息（管理员除外）</font></li>
	</p>

	<h3>上传注意事项</h3>
	<p>
	<li>图片或压缩包大于1M时，上传会较慢，请不要关闭上传窗口并耐心等待。</li>
	</p>
	<p>
	<li>如果长时间没有反应，请重新上传。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<li>查询数据：设定查询条件，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-search'">查找</a></li>
	</p>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a>，填写完成后单击保存</li>
	</p>
	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a></li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a></li>
	</p>

	<h3>操作反馈</h3>
	<p>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
	</p>
</ul>