<ul>
	<h3>专著教材填写规范</h3>
	<p>
	<li>同一个专著教材只需填写一次。</li>
	</p>
	<p>
	<li>参编者：选择主编/副主编/编委后，使用鼠标左键双击进行添加和删除编者，由上往下排序。</li>
	</p>
	<p>
	<li><font color="#ff0000">非专著/教材编者不能查看专著/教材信息（管理员除外）</font>
	</li>
	</p>

	<h3>上传注意事项</h3>
	<p>
	<li>图片或压缩包大于1M时，上传会较慢，请不要关闭上传窗口并耐心等待。如果长时间没有反应，请重新上传。</li>
	</p>

	<h3>操作方法</h3>
	<p>
	<li>添加数据：单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-add'">增加</a>，填写完成后单击保存</li>
	</p>

	<p>
	<li>修改数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-edit'">修改</a></li>
	</p>
	<p>
	<li>删除数据：勾选列表中的一项，单击<a class="easyui-linkbutton"
		data-options="iconCls:'icon-remove'">删除</a></li>
	</p>

	<h3>操作反馈</h3>
	<li>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</li>
</ul>