<div class="easyui-panel" title="教师个人信息" align="center" style="height: 100%;width:100%" data-options="tools:'#tool_information_1'">
<form  method="post" style="padding:10px;" >

	<table border="1" style="border-collapse:collapse;width:100%;" >
	<caption><b>教师业务情况登记表</b></caption>
	<!-- <thead>院系:信息学院&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;教研室:应用<thead> -->
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">姓名:</td>
			<td  style="font-size: 10px;">周小雄</td>
			<td style="font-size: 10px;">性别:</td>
			<td  style="font-size: 10px;">男</td>
			<td style="font-size: 10px;">职称:</td>
			<td  style="font-size: 10px;">助教</td>
			<td style="font-size: 10px;">职务:</td>
			<td  style="font-size: 10px;">教师</td>
		</tr>
		
	</table>

	<table border="1" style="border-collapse:collapse;width:100%;" >
		<tr style="line-height:20px;" align="center">
			<td rowspan='3' style="font-size: 10px;">完成教学工作情况</td>
			<td  style="font-size: 10px;">任教课程名</td>
			<td style="font-size: 10px;">班级</td>
			<td  style="font-size: 10px;">教材版别</td>
			<td style="font-size: 10px;">总科时</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td  style="font-size: 10px;">程序设计实习</td>
			<td  style="font-size: 10px;">信A1311</td>
			<td style="font-size: 10px;">高等教育出版社</td>
			<td  style="font-size: 10px;">76</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td  style="font-size: 10px;">程序设计实习</td>
			<td  style="font-size: 10px;">信A1311</td>
			<td style="font-size: 10px;">高等教育出版社</td>
			<td  style="font-size: 10px;">76</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td colspan='4' style="font-size: 10px;">合计课时</td>
			<td  style="font-size: 10px;">211</td>
		</tr>
</table>
<table border="1" style="border-collapse:collapse;width:100%">
		<tr style="line-height:20px;" align="center">
			<td rowspan='6' style="font-size: 10px;">学术研究情况</td>
			<td style="font-size: 10px;">专著编写教材名称</td>
			<td style="font-size: 10px;">出版单位及时间</td>
			<td style="font-size: 10px;">本人角色</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">AAA</td>
			<td style="font-size: 10px;">BBB</td>
			<td style="font-size: 10px;">CCC</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">论文篇名</td>
			<td style="font-size: 10px;">何时何刊发表</td>
			<td style="font-size: 10px;">本人角色(独著/第二作者)</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">AAA</td>
			<td style="font-size: 10px;">BBB</td>
			<td style="font-size: 10px;">CCC</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">课题名称</td>
			<td style="font-size: 10px;">批准(合作单位)</td>
			<td style="font-size: 10px;">本人角色(主持/参加)</td>
		</tr>
		<tr style="line-height:20px;" align="center">
			<td style="font-size: 10px;">AAA</td>
			<td style="font-size: 10px;">BBB</td>
			<td style="font-size: 10px;">CCC</td>
		</tr>
		
</table>
<table border="1" style="border-collapse:collapse;width:100%">
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">获奖情况</td>
			<td style="font-size: 10px;">2011年在省创新创业大赛中获得二等奖</td>
		</tr>
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">参加学术团体情况</td>
			<td style="font-size: 10px;"></td>
		</tr>
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">进修培训情况</td>
			<td style="font-size: 10px;"></td>
		</tr>
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">担任其他工作情况</td>
			<td style="font-size: 10px;"></td>
		</tr>
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">教研室意见</td>
			<td style="font-size: 10px;">(对该教师综合业务情况,课堂教学的态度,效果,教书育人等方面做出具体评价)</td>
		</tr>
		<tr style="line-height:60px;" align="center">
			<td style="font-size: 10px;">院系意见</td>
			<td style="font-size: 10px;">同意</td>
		</tr>
</table>
	<p align="left">注:<lable>1.本表一式两份,院系,教务处各一份存入教师个人业务档案<br>2.请用16K纸打印</lable></p>
</form>		
		<!-- <tr style="line-height: 50px;">
			<td style="font-size: 10px;">工号:</td>
			<td style="font-size: 10px;">14181</td>
			<td style="align:center;font-size: 10px;">姓名:</td>
			<td style="font-size: 10px;">周小雄</td>
			<td style="align:center;font-size: 10px;">出生年月:</td>
			<td><input class="easyui-datebox" type="text" name="borth"
				style="height: 21px" data-options="prompt:'输入日期',required:true"></input>
			</td>

		</tr> -->
<!-- 		<tr style="line-height: 50px;">

			<td style="font-size: 10px;">民族:</td>
			<td><input class="easyui-textbox" type="text" name="nation"
				style="height: 21px" data-options="prompt:'输入民族'"></input>
			</td>
			<td style="align:center;font-size: 10px;">政治面貌:</td>
			<td><select class="easyui-combobox" name="political_status" style="width:150px;height: 21px;">
				<option value="DY">党员</option>
				<option value="QZ">群众</option>
			</select>
			</td>
			<td style="align:center;font-size: 10px;">职称:</td>
			<td><select class="easyui-combobox" name="title" style="width:150px;height: 21px;">
				<option value="ZJ">助教</option>
				<option value="JS">讲师</option>
				<option value="FJS">副教授</option>
				<option value="JS">教授</option>
			</select>
			</td>

		</tr>
		<tr style="line-height: 50px;">
			<td style="font-size: 10px;">最后学位:</td>
			<td><select class="easyui-combobox" name="final_degree" style="width:150px;height: 21px;">
				<option value="XS">学士</option>
				<option value="SS">硕士</option>
				<option value="BS">博士</option>
			</select>
			</td>
			<td style="align:center;font-size: 10px;">最后学历:</td>
			<td><select class="easyui-combobox" name="final_education" style="width:150px;height: 21px;">
				<option value="BK">本科</option>
				<option value="YJS">研究生</option>
			</select>
			</td>
			<td style="align:center;font-size: 10px;">获得学位时间:</td>
			<td><input class="easyui-datebox" type="text" name="degree_time"
				style="height: 21px" data-options="prompt:'输入日期'"></input>
			</td>
		</tr>
		<tr style="line-height: 50px;">
			<td style="font-size: 10px;">院系:</td>
			<td><select class="easyui-combobox" name="school" style="width:150px;height: 21px;">
				<option value="XX">信息科学与技术学院</option>
				<option value="WY">外国语学院</option>
				<option value="LY">旅游与国土资源学院</option>
			</select>
			</td>
			<td style="align:center;font-size: 10px;">部门/教研室:</td>
			<td><select class="easyui-combobox" name="partment" style="width:150px;height: 21px;">
				<option value="JW">教务科</option>
				<option value="JY">教研科</option>
				<option value="JYS">教研室</option>
			</select>
			</td>
			
		</tr> -->
</div>